"""
Data Models Module

This module defines the database models using SQLModel (Pydantic + SQLAlchemy).
SQLModel provides both data validation and ORM functionality in a single class.

Models:
- Todo: Represents a single task in the user's todo list

Author: Shayan
Project: SDD-Hackathon-02 Phase-01
"""

from sqlmodel import SQLModel, Field
from datetime import datetime
from typing import Optional


class Todo(SQLModel, table=True):
    """
    Represents a single task in the user's todo list.
    
    This model defines the structure of todo items stored in the database.
    It uses SQLModel which combines Pydantic validation with SQLAlchemy ORM.
    
    Attributes:
        id (Optional[int]): Primary key, auto-generated by the database
        task (str): The description of the todo item (required, cannot be null)
        is_done (bool): Completion status of the task (default: False)
        created_at (datetime): Timestamp when the task was created (auto-generated)
        
    Example:
        todo = Todo(task="Buy groceries")
        # id=None, task="Buy groceries", is_done=False, created_at=<current_time>
    """
    id: Optional[int] = Field(default=None, primary_key=True)
    task: str = Field(sa_column_kwargs={"nullable": False})
    is_done: bool = Field(default=False)
    created_at: datetime = Field(default_factory=datetime.now)